# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Arugula' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Arugula
  pod 'Firebase/Analytics'
  pod 'FirebaseUI'
  
  # Pod for swipe view
  pod 'pop', '1.0.10'

  target 'ArugulaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArugulaUITests' do
    # Pods for testing
  end

end
platform :ios, '11.0'
